ARG BASE_IMAGE="ghcr.io/icsc-spoke2-repo/jlab:wp5-alma9-highrate-v0.1.4"
FROM ${BASE_IMAGE}

# Update conda ROOT 

RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

RUN conda install -c conda-forge icu=75.1 nodejs=20.12.2 boost root="6.38.*" -y

COPY refresh-manifest.py /opt/conda/lib/python3.11/site-packages/dask_labextension/refresh-manifest.py

ENV IMAGE_TAG=latest-boost-v3