ARG BASE_IMAGE="ghcr.io/icsc-spoke2-repo/jlab:wp5-alma9-highrate-v0.1.4"
FROM ${BASE_IMAGE}

# Update conda ROOT 

RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

RUN conda update -c conda-forge -y root
RUN conda install -c conda-forge "sqlite>=3.45"
RUN conda clean -a -y